# Generated by Django 5.1.1 on 2024-09-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayId', models.IntegerField(unique=True)),
                ('agendaTitle', models.CharField(max_length=64)),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.IntegerField()),
                ('itemDesc', models.CharField(max_length=255)),
                ('itemURL', models.CharField(max_length=1024)),
                ('completed', models.BooleanField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agenda')),
            ],
        ),
    ]
